const productFormTypes = {
  UPLOAD_PRODUCT: "UPLOAD_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  UPLOADED_PRODUCT: "UPLOADED_PRODUCT",
  UPDATED_PRODUCT: "UPDATED_PRODUCT"
};

export default productFormTypes;
