const ProductsTypes = {
  FETCHING_PRODUCTS: "FETCHING_PRODUCTS",
  FETCHED_DATA: "FETCHED_DATA",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETED_PRODUCTS: "DELETED_PRODUCTS",
  SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT"
};

export default ProductsTypes;
