export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const FETCHED_DATA = 'FETCHED_DATA';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETED_PRODUCTS = 'DELETED_PRODUCTS';
export const SET_LOADING = 'SET_LOADING';
